first-join: "<dark_red>* (playerName) has awoken in a strange place..."

first-join-dialogue:
  1: # Doesn't matter what this is called, as long as it is unique and different from the different lines
    message: "[1/3]<yellow>message one"
    delay: 0 # even if there's no delay put delay: 0
  2:
    message: "[2/3]<blue>message two"
    delay: 2
  3:
    message: "[3/3]<green>message three"
    delay: 3 # This message will send 5 seconds after the player joined, the delays stack from the previous messages




# Message that will be sent on evey subsequent join
welcome-back: "<green>* (playerName) has returned from their expedition!"
leave-message: "<red>* (playerName) left on an expedition..."
