name: RejoinRewards
version: 1.0
main: me.cookie.joinhandler.JoinHandler
description: A plugin that rewards players based on the time they were away.
api-version: 1.18
author: Cookie#8723

depend:
  - SemiCore