name: JoinHandler
version: 1.0.1
main: me.cookie.joinhandler.JoinHandler
description: Join operations.
api-version: 1.18
author: Cookie#8723
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:1.6.0'

depend:
  - CookieCore
  - WorldEdit

commands:
  spawncampfire:
    description: Spawns the first-join campfire (console only)
    usage: /spawncampfire <player>
    permission: joinhandler.spawncampfire

permissions:
  joinhandler.spawncampfire:
    default: op
    description: useless, just hides command from autocomplete.